name: Continuous Integration
on: [pull_request, push]
jobs:
  build:
    name: Build
    runs-on: ${{matrix.runs-on}}
    strategy:
      matrix:
        target: [
          aarch64-apple-darwin,
          aarch64-apple-ios,
          aarch64-linux-android,
          x86_64-apple-darwin,
          x86_64-apple-ios,
          x86_64-linux-android,
          x86_64-pc-windows-msvc,
          x86_64-unknown-linux-gnu,
        ]
        include:
          - target: aarch64-apple-darwin
            runs-on: macos-15
          - target: aarch64-apple-ios
            runs-on: macos-15
          - target: aarch64-linux-android
            runs-on: macos-15
          - target: x86_64-apple-darwin
            runs-on: macos-15
          - target: x86_64-apple-ios
            runs-on: macos-15
          - target: x86_64-linux-android
            runs-on: macos-15
          - target: x86_64-pc-windows-msvc
            runs-on: windows-2022
          - target: x86_64-unknown-linux-gnu
            runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Generate .cargo/config.toml
        env:
          CARGO_CONFIG_TOML: ${{secrets.CARGO_CONFIG_TOML}}
        run: |
          mkdir .cargo
          echo "${CARGO_CONFIG_TOML}" >> .cargo/config.toml
      - name: Build breakpad.rs
        run: cargo build --target=${{matrix.target}}
